# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  bigsheepdev.live:
    site_hosts:
      - canonical: bigsheepdev.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: baldur@bigsheepstudio.dk
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
